import {VStack} from 'native-base';
import React from 'react';
import {StyleSheet, Text, View} from 'react-native';
import {textStyles} from '../../../docs/config';
import {Button} from '../../components/Button';

export interface IManageData {}

export const ManageData: React.FC<IManageData> = ({}) => {
  return (
    <VStack paddingX={5} marginTop={5}>
      <VStack>
        <View>
          <Text style={styles.title}>Download your data</Text>

          <Text style={styles.description}>
            You own your data. Tap the button below to download a copy of your
            data
          </Text>
        </View>
        <View style={{alignItems: 'center', marginTop: 10}}>
          <Button
            style={{width: '60%'}}
            title="Download my data"
            onPress={() => {}}
          />
        </View>
        <VStack marginTop={5}>
          <View>
            <Text style={styles.title}>Delete your account</Text>
            <Text style={styles.description}>
              Use this only if you want to permanently delete your account &
              data from our system.
            </Text>
            <Text style={[styles.note]}>
              Note: due to the immutable nature of distributed ledger
              technology, network nodes operated by the community may still
              retain historical transactions generated by your account, however
              your personally identifiable information such as your name,
              e-mail, your key-value storage etc will be removed.
            </Text>
            <Text style={[styles.note]}>
              Any of your digital assets will be lost.
            </Text>
          </View>
          <View style={{alignItems: 'center', marginTop: 10}}>
            <Button
              style={{backgroundColor: 'red', width: '60%'}}
              title="Delete my account"
              onPress={() => {}}
            />
          </View>
        </VStack>
      </VStack>
    </VStack>
  );
};

const styles = StyleSheet.create({
  title: {
    fontFamily: textStyles.semiBoldFont,
    color: 'black',
    fontSize: 16,
    marginVertical: 5,
  },
  description: {
    fontFamily: textStyles.regularFont,
    color: 'black',
  },
  note: {
    color: 'black',
    marginTop: 5,
    fontStyle: 'italic',
    fontSize: 12,
  },
});
